services:
  app:
    build:
      context: .
      target: development
    container_name: api-qasma
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - maildev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
  mongo:
    image: mongo:latest
    container_name: api-qasma-mongo
    ports:
      - '${MONGO_CLIENT_PORT}:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '${REDIS_SERVER_PORT}:6379'
  maildev:
    image: maildev/maildev
    container_name: api-qasma-maildev
    ports:
      - '${MAILDEV_SMTP}:1025'
      - '${MAILDEV_WEBAPP_PORT}:1080'
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:1080']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo-data:
