services:
  app:
    build:
      context: .
      target: production
    container_name: api-qasma
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '${REDIS_SERVER_PORT}:6379'
