services:
  app:
    build:
      context: .
      target: production
    container_name: api-qasma
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '${REDIS_SERVER_PORT}:6379'
